### PR TITLE
add save theme functionality and fix result color issue in dark mode

### LINKED ISSUE #44: Clear subscribe events once the user unsubscribes
Subscribe events are not being cleared once the user UnSubscribes. This results in showing events in different screens.

How to Reproduce:

1. Start a router & register a procedure.
2. Call the procedure multiple times.
3. Now, UnSubscribe the procedure.

The events will still be there.

### PR DESCRIPTION
**Pull request by shakeebkhan66**
closes #44

### CODE REVIEW

File: lib/screens/mobile/mobile_home.dart [hunk 1]
```diff
@@ -771,9 +766,10 @@ class _MobileHomeScaffoldState extends State<MobileHomeScaffold> with TickerProv
   Future<void> _unSubscribe(int index, Session? session, var sub) async {
     await session?.unsubscribe(sub);
     setState(() {
-      _tabData[index].sendButtonText = "Subscribe";
+      _tabData[index].sendButtonText = "Call";
```
Comment (muzzammilshahid) [inline lib/screens/mobile/mobile_home.dart:769]: revert this change

File: lib/screens/mobile/mobile_home.dart [hunk 2]
```diff
@@ -760,7 +755,7 @@ class _MobileHomeScaffoldState extends State<MobileHomeScaffold> with TickerProv
   Future<void> _unRegister(int index, Session? session, var reg) async {
     await session?.unregister(reg);
     setState(() {
-      _tabData[index].sendButtonText = "Register";
+      _tabData[index].sendButtonText = "Call";
```
Comment (muzzammilshahid) [inline lib/screens/mobile/mobile_home.dart:758]: revert this change

**Review by muzzammilshahid — CHANGES_REQUESTED** [review]

**Review by muzzammilshahid — APPROVED** [review]

**Review by Mahad-10 — APPROVED** [review]
